const HEALTH_CHECK_PACKAGES = Object.freeze([
  "Executive Health Check - Dependent - Above 40 years - Female (Year 2025-26)",
  "Executive Health Check - Dependent - 60 & Above - Male (Year 2025-26)",
  "Executive Health Check (EHC) - Dependent- 60 & Above-Female (24-25)",
  "Platinum Health check - Dependent-Female (24-25)",
  "Platinum Health check - Employee-Male (24-25)",
  "Executive Health Check -Dependent- Below 40 years (24-25)",
  "Annual Health Check Package  - Female Dependent - GlobalLogic",
  "Executive Health Check - Dependent - 60 & Above - Female (Year 2025-26)",
  "Executive Health Check -Dependent- 60 & Above-Female (24-25)",
  "Platinum Health check - Dependent - Female (Year 2025-26)",
  "Executive Health Check - Employee -Above 40 years - Male (24-25)",
  "Platinum Health check - Employee-Female (24-25)",
  "Platinum Health check - Dependent-Male (24-25)",
  "Executive Health Check - Dependent- Above 40 years - Male (24-25)",
  "Executive Health Check -Employee- Below 40 years (24-25)",
  "Executive Health Check -Dependent- 60 & Above - Male (24-25)",
  "Executive Health Check (EHC) -Dependent- 60 & Above - Male (24-25)",
  "Executive Health Check -Employee- 60 & Above - Male (24-25)",
  "Executive Health Check - Dependent - Below 40 years (Year 2025-26)",
  "Hyundai Eng - Health Check-up - Male Below 40",
  "Executive Health Check - Employee - Above 40 years - Male (Year 2025-26)",
  "Executive Health Check (EHC) - Employee -Above 40 years - Female (24-25)",
  "Executive Health Check (EHC) - Dependent- Above 40 years - Male (24-25)",
  "Executive Health Check -Employee- 60 & Above-Female (24-25)",
  "Executive Health Check - Employee -Above 40 years - Female (24-25)",
  "Executive Health Check - Employee - Above 40 years - Female (Year 2025-26)",
  "Hyundai-Annual Health check-Only Radiology-Below 40-Female",
  "Hyundai Radiology at Centre-Above 40-Female Package",
  "Hyundai-Annual Health check-Complete Package-Above 40-Male",
  "Executive Health Check - Employee - 60 & Above - Male (Year 2025-26)",
  "Platinum Health check - Dependent - Male (Year 2025-26)",
  "Executive Health Check - Dependent -Above 40 years - Female (24-25)",
  "Executive Health Check (EHC) - Dependent -Above 40 years - Female (24-25)",
  "Xcube Executive health check Male - Pathology & Radiology",
  "JCI-Annual Health Check Above 35 Male",
  "Executive Health Check - Employee - Below 40 years (Year 2025-26)",
  "Executive Health Check (EHC) - Employee -Above 40 years - Male (24-25)",
  "Annual Health Check Package Female - GlobalLogic",
  "Executive Health Check (EHC) -Dependent- Below 40 years (24-25)",
  "Platinum Health check - Employee - Male (Year 2025-26)",
  "Executive Health Check - Dependent - Above 40 years - Male (Year 2025-26)",
  "Executive Health Check - Employee - 60 & Above - Female (Year 2025-26)",
  "Supreme Industries-Health check Above 40 Female",
  "Supreme Industries-Health check Above 40 Male",
  "Platinum Health check - Employee - Female (Year 2025-26)",
  "Hyundai Blood Sample Collection at Home-Above 40-Male Package",
  "L&T - AHC above 35 Years for Male - 2D Echo Package",
  "Cisco - Executive Health Check Male Package",
  "Hyundai Eng - Health Check-up - Male Above 40",
  "Kelvion - PRE-EMPLOYMENT HEALTH CHECK UP  Package",
  "Supreme Industries-Health check Below 40",
  "Gym Fitness Health Check above 40 Module Male Package",
  "Annual Health Check - Cisco 40 and above Female",
  "Executive Health Check (EHC) -Employee- Below 40 years (24-25)",
  "Platinum Health check (PHC) - Dependent-Female (24-25)",
  "JCI-Annual Health Check Below 35",
  "Hyundai Complete CheckUp at Centre-Above 40-Female Package",
  "Xcube Executive health check Female - Pathology",
  "HCL TASL - ANNUAL HEALTH CHECK (AHC)",
  "Abbott - Home Collection - Dependent - Male - Pathology AHC Package",
  "CISCO System Test Package - Below 40 Years",
  "ST Micro-Executive Health Check Below 40 years",
  "Takenaka - Annual Health check Package - Above 35 - Male",
  "Hyundai Eng - Health Check-up - Female Above 40",
  "Hyundai-Annual Health check-Pathology-Above 40-Male",
  "Platinum Health check (PHC) - Employee-Male (24-25)",
  "Nagarro - Annual Health check Male (HSC)",
  "Platinum Health check (PHC) - Dependent-Male (24-25)",
  "Platinum Health check (PHC) - Employee-Female (24-25)",
  "Nagarro - Annual Health check Dependent Male (Center)",
  "Executive Health Check (EHC) -Employee- 60 & Above-Female (24-25)",
  "HCL TASL - ANNUAL HEALTH CHECK",
  "Xcube Executive health check Female - Radiology",
  "Executive Health Check (EHC) -Employee- 60 & Above - Male (24-25)",
  "Hyundai Radiology at Centre-Below 40-Female Package",
  "ADVANCED THYROID PROFILE Package",
  "Health Check Up -Adult Package",
  "Annual Health Check Package - Male Dependent - GlobalLogic",
  "Accel Annual Health Check Package - Female",
  "Add-On Above 60 to Platinum Pathology Only Package",
  "Nagarro - Annual Health check Female (HSC)",
  "Amphenol Pre-Employment Health Check Package - Male",
  "Gym Fitness Health Check below 40 Module Female Package",
  "Nagarro- Annual Health check Female (Center)",
  "Senior Citizen Full Body Checkup - Male (Advance) Package",
  "Cisco - Executive Health Check Female Package",
  "Abbott Health Check - Male Package",
  "Gym Fitness Health Check Package Male (GFHCP)",
  "L&T - AHC above 35 Years for Male Package",
  "Annual Health Check - Cisco Below 40 Female",
  "Hyundai Complete CheckUp at Centre-Above 40-Male Package",
  "Amphenol Annual Health Check Package Dependent - Male",
  "Annual Health Check - Cisco Below 40 Male",
  "Abbott - Center Visit - Dependent - Female - Complete AHC Package",
  "Amphenol Pre-Employment Health Check Package - Female",
  "Gym Fitness Health Check below 40 Module Male Package",
  "Hyundai-Annual Health check-Pathology -Female",
  "TASL - Executive Health check above 45",
  "Hyundai-Annual Health check-Only Radiology-Male",
  "Pre- Marital Health Check up Advanced ( Male) Package",
  "Takenaka - Annual Health check Package - Above 35 - Female",
  "Takenaka - Annual Health check Package - Below 35 - Male",
  "Annual Health Check Package Male - GlobalLogic",
  "Hyundai Complete CheckUp at Centre-Below 40-Female Package",
  "Health check-GMR Male",
  "Xcube Executive health check Male - Pathology",
  "Hyundai-Annual Health check-Only Radiology-Above 40-Female",
  "Blue Star-HealthCheck Female Package",
  "Takenaka - Annual Health check - Below 35 - Male Package",
  "Hyundai Eng - Health Check-up - Female Below 40",
  "Abbott - Home Collection - Dependent - Female - Pathology AHC Package",
  "ST Micro-Executive Health Check Above 40 years - Female",
  "Hyundai-Annual Health check-Complete Package-Above 40-Female",
  "Xcube Executive health check Female - Pathology & Radiology",
  "Volo - Health check",
  "Hyundai-Annual Health check-Complete Package-Below 40-Female",
  "Vidyagyan Health Check - Package",
  "JCI- Annual Health Check Above 35 Female",
  "Hyundai Blood Sample Collection at Home-Below 40-Male Package",
  "ST Micro- Health Check Above 40 years - Male",
  "Nagarro - Annual Health check Male (Center)",
  "Health check-GMR Female",
  "Xcube Executive health check Male - Radiology",
  "Annual Health Check - Cisco 40 and Above Male",
  "Accel Annual Health Check Package - Male",
  "Hyundai Complete CheckUp at Centre-Below 40-Male Package",
  "Takenaka - Annual Health check Package - Below 35 - Female",
  "Hyundai-Annual Health check-Pathology-Below 40-Male",
  "Blue Star-HealthCheck Male Package",
  "Hyundai-Annual Health check-Complete Package-Below 40-Male",
  "Nagarro- Annual Health check Dependent Female (Center)",
  "Health Check Up -Child Package",
]);

module.exports = { HEALTH_CHECK_PACKAGES };
